const Slider = () => {
    return (
        <>
<div className="main-slider style-two default-banner">
  <div className="tp-banner-container">
    <div className="tp-banner">
      <div id="rev_slider_1014_1_wrapper" className="rev_slider_wrapper fullscreen-container" data-alias="typewriter-effect" data-source="gallery">
        {/* START REVOLUTION SLIDER 5.3.0.2 */}
        <div id="rev_slider_1014_1" className="rev_slider fullscreenbanner" style={{display: 'none'}} data-version="5.3.0.2">
          <ul>
            {/* SLIDE 1 */}
            <li data-index="rs-1000" data-transition="zoomin" data-slotamount={7} data-hideafterloop={0} data-hideslideonmobile="off" data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed={2000} data-thumb="images/main-slider/slide1.jpg" data-rotate={0} data-saveperformance="off" data-title="Love it?" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
              {/* MAIN IMAGE */}
              <img src={require("../../assets/front/images/main-slider/slide1.jpg").default} alt="slider1" data-bgposition="center center" data-kenburns="on" data-duration={10000} data-ease="Linear.easeNone" data-scalestart={100} data-scaleend={120} data-rotatestart={0} data-rotateend={0} data-offsetstart="0 -500" data-offsetend="0 500" data-bgparallax={10} className="rev-slidebg" data-no-retina />
              {/* LAYER NR. 1 [ for overlay ] */}
              <div className="tp-caption tp-shape tp-shapewrapper " id="slide-100-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;from&quot;:&quot;opacity:0;&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:0,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 12, backgroundColor: 'rgba(0, 0, 0, 0.40)', borderColor: 'rgba(0, 0, 0, 0)', borderWidth: 0}}> </div>
              {/* LAYER NR. 2 [ for title ] */}
              <div className="tp-caption  tp-resizeme" id="slide-100-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['190','190','190','190']" data-fontsize="['50','50','50','50']" data-lineheight="['70','70','70','70']" data-width="['700','700','700','700']" data-height="['none','none','none','none']" data-whitespace="['normal','normal','normal','normal']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;speed&quot;:2000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:750,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;y:[100%];&quot;,&quot;mask&quot;:&quot;x:inherit;y:inherit;s:inherit;e:inherit;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 13, fontSize: 65, lineHeight: 60, fontWeight: 700, color: 'rgba(255, 255, 255, 1.00)', borderWidth: 0}}> <span style={{fontFamily: '"Poppins" ,sans-serif'}}>You Booking Our<br /> passage to the future.</span> </div>
              {/* LAYER NR. 3 [ for paragraph] */}
              {/* LAYER NR. 4 [ for readmore botton ] */}
              <div className="tp-caption tp-resizeme" id="slide-100-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['450','450','450','550']" data-fontsize="['none','none','none','none']" data-lineheight="['none','none','none','none']" data-width="['700','700','700','700']" data-height="['none','none','none','none']" data-whitespace="['normal','normal','normal','normal']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;speed&quot;:2000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:750,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;y:[100%];&quot;,&quot;mask&quot;:&quot;x:inherit;y:inherit;s:inherit;e:inherit;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 13}}> <a href="javascript:void(0);" className="site-button"><span>Read More</span></a> </div>
            </li>
            {/* SLIDE 1 */}
            <li data-index="rs-2000" data-transition="zoomin" data-slotamount={7} data-hideafterloop={0} data-hideslideonmobile="off" data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed={2000} data-thumb="images/main-slider/slide1.jpg" data-rotate={0} data-saveperformance="off" data-title="Love it?" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
              {/* MAIN IMAGE */}
              <img src={require("../../assets/front/images/main-slider/slide2.jpg").default} alt="slider2" data-bgposition="center center" data-kenburns="on" data-duration={10000} data-ease="Linear.easeNone" data-scalestart={100} data-scaleend={120} data-rotatestart={0} data-rotateend={0} data-offsetstart="0 -500" data-offsetend="0 500" data-bgparallax={10} className="rev-slidebg" data-no-retina />
              {/* LAYER NR. 1 [ for overlay ] */}
              <div className="tp-caption tp-shape tp-shapewrapper " id="slide-200-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;from&quot;:&quot;opacity:0;&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:0,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 12, backgroundColor: 'rgba(0, 0, 0, 0.40)', borderColor: 'rgba(0, 0, 0, 0)', borderWidth: 0}}> </div>
              {/* LAYER NR. 2 [ for title ] */}
              <div className="tp-caption  tp-resizeme" id="slide-200-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['190','190','190','190']" data-fontsize="['50','50','50','50']" data-lineheight="['70','70','70','70']" data-width="['700','700','700','700']" data-height="['none','none','none','none']" data-whitespace="['normal','normal','normal','normal']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;speed&quot;:2000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:750,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;y:[100%];&quot;,&quot;mask&quot;:&quot;x:inherit;y:inherit;s:inherit;e:inherit;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 13, fontSize: 65, lineHeight: 60, fontWeight: 700, color: 'rgba(255, 255, 255, 1.00)', borderWidth: 0}}> <span style={{fontFamily: '"Poppins" ,sans-serif'}}>You Focus On Your <br />
                  Business</span> </div>
              {/* LAYER NR. 3 [ for paragraph] */}
              {/* LAYER NR. 4 [ for readmore botton ] */}
              <div className="tp-caption tp-resizeme" id="slide-200-layer-4" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['450','450','450','550']" data-fontsize="['none','none','none','none']" data-lineheight="['none','none','none','none']" data-width="['700','700','700','700']" data-height="['none','none','none','none']" data-whitespace="['normal','normal','normal','normal']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;from&quot;:&quot;y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:[100%];s:inherit;e:inherit;&quot;,&quot;speed&quot;:2000,&quot;to&quot;:&quot;o:1;&quot;,&quot;delay&quot;:750,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:1000,&quot;to&quot;:&quot;y:[100%];&quot;,&quot;mask&quot;:&quot;x:inherit;y:inherit;s:inherit;e:inherit;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 13}}> <a href="javascript:void(0);" className="site-button"><span>Read More</span></a> </div>
            </li>
          </ul>
          <div className="tp-bannertimer tp-bottom" style={{visibility: 'hidden !important'}} />
        </div>
      </div>
      {/* END REVOLUTION SLIDER */}
    </div>
  </div>
</div>
{/* Slider END */}

        </>
    )
}

export default Slider
